name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test-x.yml
    secrets: inherit
    